name: Create release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name (e.g. v1.0.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Zip files for release
        run: |
          repo_name="${GITHUB_REPOSITORY#*/}"
          zip -r "$repo_name.zip" data pack.mcmeta
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          repo_name="${GITHUB_REPOSITORY#*/}"
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              "$repo_name.zip"
